#!/usr/bin/env node
import { promises as fs } from "node:fs";
import path from "node:path";

import {
  buildCliContext,
  validateRequiredRoots,
} from "../core/workspace-context.mjs";
import { parseArgs, resolveMode } from "../core/cli-args.mjs";
import { emitResult } from "../core/result-envelope.mjs";
import { t } from "../core/i18n-strings.mjs";
import { pathExists } from "../core/topic-files.mjs";
import {
  appendProfileEntry,
  appendTopicEntry,
  writePeriodDigest,
  promoteStreamItem,
  retireProfileEntry,
  updateProfileEntry,
  compactProfileHistory,
  restoreProfileEntry,
  ensureTodoFile,
  readTodoList,
  addTodoItem,
  toggleTodoItem,
  resolveTodoRelPath,
} from "../../lib/kernel-api.mjs";

// ── promote ─────────────────────────────────────────────────────────────────

async function promote({ sourcePath, targetSlug, mode }, ctxObj) {
  if (!sourcePath) throw new Error(t("error.sourcePathRequired"));
  if (!targetSlug) throw new Error(t("error.slugRequired"));
  const sourceAbsPath = path.join(ctxObj.userWorkspaceRoot, sourcePath);
  if (!await pathExists(sourceAbsPath)) {
    throw new Error(t("error.sourcePathNotFound", { path: sourcePath }));
  }
  const content = await fs.readFile(sourceAbsPath, "utf8");
  const title = path.basename(sourcePath, ".md");

  const item = {
    path: sourceAbsPath,
    content,
    title,
  };

  const target = {
    layer: "topics",
    slug: targetSlug,
  };

  // Contract declares supports_dry_run — preview mode must not write.
  if (mode === "preview") {
    const topicsRel = `memory/topics/${targetSlug}.md`;
    return {
      command: "promote",
      mode,
      sourcePath,
      targetSlug,
      targetPath: topicsRel,
      applied: false,
      preview: true,
      note: "dry-run: source and target validated, nothing written",
    };
  }

  const evidence = promoteStreamItem({
    workspaceRoot: ctxObj.userWorkspaceRoot,
    item,
    target,
  });

  return {
    command: "promote",
    mode,
    sourcePath,
    targetSlug,
    targetPath: ctxObj.userWorkspaceRoot ? path.relative(ctxObj.userWorkspaceRoot, evidence.target_path) : evidence.target_path,
    applied: mode === "auto",
    evidence,
  };
}

// ── digest ──────────────────────────────────────────────────────────────────

async function digest({ period }, ctxObj) {
  if (!period) throw new Error(t("error.periodRequired"));
  // UTR is a **deterministic non-AI adapter** (no model). Product AI digests
  // are generated by Desktop suggest-engine → applySuggestion (confirm first).
  // Do NOT write "待 AI 生成" pollution — write an explicit adapter stub that
  // is honest about origin, or skip when writePeriodDigest rejects pollution.
  const body = `# ${period} 周期反思

> UTR 确定性 adapter 骨架（非 AI 生成）。真实 AI 周期反思请用 Desktop 建议管线确认后写入。

## 本周要点

- （adapter）本条由 UTR \`memory digest\` 创建，内容需由用户或 Desktop AI 补全。
`;

  const evidence = writePeriodDigest({
    workspaceRoot: ctxObj.userWorkspaceRoot,
    period,
    body,
  });

  return {
    command: "digest",
    period,
    adapter: "utr-deterministic",
    note: "UTR has no AI model; Desktop suggest-engine is the product AI path",
    targetPath: ctxObj.userWorkspaceRoot ? path.relative(ctxObj.userWorkspaceRoot, evidence.target_path || evidence.targetPath || "") : (evidence.target_path || evidence.targetPath),
    wroteFiles: evidence.wroteFiles !== false && evidence.operation !== "skip",
    evidence,
  };
}

// ── append-profile ──────────────────────────────────────────────────────────

async function appendProfile({ section, content }, ctxObj) {
  if (!section) throw new Error(t("error.sectionRequired"));
  if (!content) throw new Error(t("error.contentRequired"));
  const evidence = appendProfileEntry({
    workspaceRoot: ctxObj.userWorkspaceRoot,
    entry: { section, content },
  });

  return {
    command: "append-profile",
    section,
    targetPath: ctxObj.userWorkspaceRoot ? path.relative(ctxObj.userWorkspaceRoot, evidence.target_path) : evidence.target_path,
    evidence,
  };
}

// ── append-topic ────────────────────────────────────────────────────────────

async function appendTopic({ slug, content }, ctxObj) {
  if (!slug) throw new Error(t("error.slugRequired"));
  if (!content) throw new Error(t("error.contentRequired"));
  const evidence = appendTopicEntry({
    workspaceRoot: ctxObj.userWorkspaceRoot,
    slug,
    entry: { content },
  });

  return {
    command: "append-topic",
    slug,
    targetPath: ctxObj.userWorkspaceRoot ? path.relative(ctxObj.userWorkspaceRoot, evidence.target_path) : evidence.target_path,
    evidence,
  };
}

// ── retire-profile ──────────────────────────────────────────────────────────

async function retireProfile({ match, section, reason, mode }, ctxObj) {
  if (!match) throw new Error(t("error.matchRequired") || "match required");
  if (mode === "preview") {
    return {
      command: "retire-profile",
      mode,
      match,
      applied: false,
      preview: true,
      note: "dry-run: would retire matching live fact into ## 历史记录",
    };
  }
  const evidence = retireProfileEntry({
    workspaceRoot: ctxObj.userWorkspaceRoot,
    match,
    section: section || undefined,
    reason: reason || undefined,
    actor: "user",
    confirmed: true,
  });
  return {
    command: "retire-profile",
    match,
    targetPath: ctxObj.userWorkspaceRoot ? path.relative(ctxObj.userWorkspaceRoot, evidence.target_path || evidence.targetPath || "") : (evidence.target_path || evidence.targetPath),
    evidence,
  };
}

// ── update-profile ──────────────────────────────────────────────────────────

async function updateProfile({ match, content, section, mode }, ctxObj) {
  if (!match) throw new Error(t("error.matchRequired") || "match required");
  if (!content) throw new Error(t("error.contentRequired"));
  if (mode === "preview") {
    return {
      command: "update-profile",
      mode,
      match,
      applied: false,
      preview: true,
      note: "dry-run: would replace matching live fact in place (superseded wording archived)",
    };
  }
  const evidence = updateProfileEntry({
    workspaceRoot: ctxObj.userWorkspaceRoot,
    match,
    content,
    section: section || undefined,
    actor: "user",
    confirmed: true,
  });
  return {
    command: "update-profile",
    match,
    targetPath: ctxObj.userWorkspaceRoot ? path.relative(ctxObj.userWorkspaceRoot, evidence.target_path || evidence.targetPath || "") : (evidence.target_path || evidence.targetPath),
    evidence,
  };
}

// ── compact-history ─────────────────────────────────────────────────────────

async function compactHistory({ threshold, mode }, ctxObj) {
  if (mode === "preview") {
    return {
      command: "compact-history",
      mode,
      applied: false,
      preview: true,
      note: "dry-run: would collapse near-dup history rows keeping the newest",
    };
  }
  const evidence = compactProfileHistory({
    workspaceRoot: ctxObj.userWorkspaceRoot,
    threshold: threshold != null && threshold !== "" ? Number(threshold) : undefined,
    actor: "user",
    confirmed: true,
  });
  return {
    command: "compact-history",
    targetPath: ctxObj.userWorkspaceRoot ? path.relative(ctxObj.userWorkspaceRoot, evidence.target_path || evidence.targetPath || "") : (evidence.target_path || evidence.targetPath),
    evidence,
  };
}

// ── restore-profile ─────────────────────────────────────────────────────────

async function restoreProfile({ match, section, mode }, ctxObj) {
  if (!match) throw new Error(t("error.matchRequired") || "match required");
  if (mode === "preview") {
    return {
      command: "restore-profile",
      mode,
      match,
      applied: false,
      preview: true,
      note: "dry-run: would restore archived fact back into an active section",
    };
  }
  const evidence = restoreProfileEntry({
    workspaceRoot: ctxObj.userWorkspaceRoot,
    match,
    section: section || undefined,
    actor: "user",
    confirmed: true,
  });
  return {
    command: "restore-profile",
    match,
    targetPath: ctxObj.userWorkspaceRoot ? path.relative(ctxObj.userWorkspaceRoot, evidence.target_path || evidence.targetPath || "") : (evidence.target_path || evidence.targetPath),
    evidence,
  };
}

// ── list-todos ──────────────────────────────────────────────────────────────

async function listTodos({ completed, limit }, ctxObj) {
  ensureTodoFile(ctxObj.userWorkspaceRoot);
  const list = readTodoList(ctxObj.userWorkspaceRoot);
  const items = Array.isArray(list?.items) ? list.items : [];
  const includeCompleted = completed === true || completed === "true";
  const max = Number(limit) > 0 ? Number(limit) : 50;
  const filtered = includeCompleted ? items : items.filter((i) => !i.done);
  return {
    command: "list-todos",
    targetPath: resolveTodoRelPath(ctxObj.userWorkspaceRoot),
    total: items.length,
    activeCount: items.filter((i) => !i.done).length,
    completedCount: items.filter((i) => i.done).length,
    items: filtered.slice(0, max),
  };
}

// ── add-todo ────────────────────────────────────────────────────────────────

async function addTodo({ text, items, dueDate, mode }, ctxObj) {
  let list = [];
  if (items) {
    try {
      const parsed = JSON.parse(items);
      if (Array.isArray(parsed)) list = parsed.map((x) => String(x));
      else if (typeof parsed === "string") list = [parsed];
      // non-array/string JSON (e.g. 42) is not a todo payload — ignore it
    } catch {
      // not JSON — treat the raw string as a single todo text
      list = [String(items)];
    }
  }
  if (text) list.push(String(text));
  list = list.map((s) => String(s).trim()).filter(Boolean);
  if (list.length === 0) throw new Error(t("error.contentRequired"));

  const targetPath = resolveTodoRelPath(ctxObj.userWorkspaceRoot);
  // preview must short-circuit BEFORE any engine write — graded-confirm
  // policy writes content through even in "confirm" mode.
  if (mode === "preview") {
    return {
      command: "add-todo",
      mode,
      preview: true,
      applied: false,
      targetPath,
      wouldAdd: list.map((entry) =>
        dueDate && !entry.includes("📅") ? `${entry} 📅 ${dueDate}` : entry,
      ),
      note: "dry-run: would add todo item(s)",
    };
  }

  ensureTodoFile(ctxObj.userWorkspaceRoot);
  const added = [];
  const skipped = [];
  let lastEvidence = null;
  for (const entry of list) {
    const body = dueDate && !entry.includes("📅") ? `${entry} 📅 ${dueDate}` : entry;
    const r = addTodoItem(ctxObj.userWorkspaceRoot, body, {
      actor: "ai",
      dueDate: dueDate || undefined,
    });
    if (r?.ok && r.item) {
      added.push(r.item);
      if (r.writebackEvidence) lastEvidence = r.writebackEvidence;
    } else {
      skipped.push({ text: entry, reason: r?.reason || "rejected" });
    }
  }

  return {
    command: "add-todo",
    mode,
    targetPath,
    addedCount: added.length,
    added,
    skipped,
    applied: added.length > 0,
    ...(lastEvidence ? { evidence: lastEvidence } : {}),
  };
}

// ── toggle-todo ─────────────────────────────────────────────────────────────

async function toggleTodo({ idOrText, mode }, ctxObj) {
  if (!idOrText) throw new Error(t("error.contentRequired"));
  ensureTodoFile(ctxObj.userWorkspaceRoot);
  const list = readTodoList(ctxObj.userWorkspaceRoot);
  const items = Array.isArray(list?.items) ? list.items : [];
  const target = items.find(
    (i) => i.id === idOrText || i.text === idOrText || i.text.includes(idOrText),
  );
  if (!target) {
    return {
      command: "toggle-todo",
      mode,
      ok: false,
      targetPath: resolveTodoRelPath(ctxObj.userWorkspaceRoot),
      error: `no matching todo: ${idOrText}`,
    };
  }
  if (mode === "preview") {
    return {
      command: "toggle-todo",
      mode,
      ok: true,
      preview: true,
      applied: false,
      targetPath: resolveTodoRelPath(ctxObj.userWorkspaceRoot),
      match: { id: target.id, text: target.text, done: target.done },
      note: "dry-run: would toggle completion",
    };
  }
  const r = toggleTodoItem(ctxObj.userWorkspaceRoot, target.id, undefined, {
    actor: "ai",
  });
  return {
    command: "toggle-todo",
    mode,
    ok: Boolean(r?.ok),
    targetPath: resolveTodoRelPath(ctxObj.userWorkspaceRoot),
    match: { id: target.id, text: target.text, wasDone: target.done },
    nowCompleted: !target.done,
    ...(r?.writebackEvidence ? { evidence: r.writebackEvidence } : {}),
  };
}

// ── dispatcher ─────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv.slice(2));

  const roots = validateRequiredRoots(args);
  const ctxObj = buildCliContext(roots);
  const mode = resolveMode(args);

  let data;
  switch (args.command) {
    case "promote":
      data = await promote({ sourcePath: args.sourcePath, targetSlug: args.targetSlug, mode }, ctxObj);
      break;
    case "digest":
      data = await digest({ period: args.period }, ctxObj);
      break;
    case "append-profile":
      data = await appendProfile({ section: args.section, content: args.content }, ctxObj);
      break;
    case "append-topic":
      data = await appendTopic({ slug: args.slug, content: args.content }, ctxObj);
      break;
    case "retire-profile":
      data = await retireProfile({ match: args.match, section: args.section, reason: args.reason, mode }, ctxObj);
      break;
    case "update-profile":
      data = await updateProfile({ match: args.match, content: args.content, section: args.section, mode }, ctxObj);
      break;
    case "compact-history":
      data = await compactHistory({ threshold: args.threshold, mode }, ctxObj);
      break;
    case "restore-profile":
      data = await restoreProfile({ match: args.match, section: args.section, mode }, ctxObj);
      break;
    case "list-todos":
      data = await listTodos({ completed: args.completed, limit: args.limit }, ctxObj);
      break;
    case "add-todo":
      data = await addTodo({ text: args.text, items: args.items, dueDate: args.dueDate, mode }, ctxObj);
      break;
    case "toggle-todo":
      data = await toggleTodo({ idOrText: args.idOrText, mode }, ctxObj);
      break;
    default:
      throw new Error(t("error.unknownCommand", { command: args.command || "(empty)" }));
  }

  emitResult(data, args.format);
}

main().catch((error) => {
  console.error(error.message || String(error));
  process.exitCode = 1;
});
