#!/usr/bin/env node
import { promises as fs } from "node:fs";
import path from "node:path";

import {
  buildCliContext,
  validateRequiredRoots,
} from "../core/workspace-context.mjs";
import { parseArgs, resolveMode } from "../core/cli-args.mjs";
import { emitResult } from "../core/result-envelope.mjs";
import { t } from "../core/i18n-strings.mjs";
import { pathExists } from "../core/topic-files.mjs";
import {
  appendProfileEntry,
  appendTopicEntry,
  writePeriodDigest,
  promoteStreamItem,
} from "../../lib/kernel-api.mjs";

// ── promote ─────────────────────────────────────────────────────────────────

async function promote({ sourcePath, targetSlug, mode }, ctxObj) {
  if (!sourcePath) throw new Error(t("error.sourcePathRequired"));
  if (!targetSlug) throw new Error(t("error.slugRequired"));
  const sourceAbsPath = path.join(ctxObj.userWorkspaceRoot, sourcePath);
  if (!await pathExists(sourceAbsPath)) {
    throw new Error(t("error.sourcePathNotFound", { path: sourcePath }));
  }
  const content = await fs.readFile(sourceAbsPath, "utf8");
  const title = path.basename(sourcePath, ".md");

  const item = {
    path: sourceAbsPath,
    content,
    title,
  };

  const target = {
    layer: "topics",
    slug: targetSlug,
  };

  const evidence = promoteStreamItem({
    workspaceRoot: ctxObj.userWorkspaceRoot,
    item,
    target,
  });

  return {
    command: "promote",
    mode,
    sourcePath,
    targetSlug,
    targetPath: ctxObj.userWorkspaceRoot ? path.relative(ctxObj.userWorkspaceRoot, evidence.target_path) : evidence.target_path,
    applied: mode === "auto",
    evidence,
  };
}

// ── digest ──────────────────────────────────────────────────────────────────

async function digest({ period }, ctxObj) {
  if (!period) throw new Error(t("error.periodRequired"));
  // UTR is a **deterministic non-AI adapter** (no model). Product AI digests
  // are generated by Desktop suggest-engine → applySuggestion (confirm first).
  // Do NOT write "待 AI 生成" pollution — write an explicit adapter stub that
  // is honest about origin, or skip when writePeriodDigest rejects pollution.
  const body = `# ${period} 周期反思

> UTR 确定性 adapter 骨架（非 AI 生成）。真实 AI 周期反思请用 Desktop 建议管线确认后写入。

## 本周要点

- （adapter）本条由 UTR \`memory digest\` 创建，内容需由用户或 Desktop AI 补全。
`;

  const evidence = writePeriodDigest({
    workspaceRoot: ctxObj.userWorkspaceRoot,
    period,
    body,
  });

  return {
    command: "digest",
    period,
    adapter: "utr-deterministic",
    note: "UTR has no AI model; Desktop suggest-engine is the product AI path",
    targetPath: ctxObj.userWorkspaceRoot ? path.relative(ctxObj.userWorkspaceRoot, evidence.target_path || evidence.targetPath || "") : (evidence.target_path || evidence.targetPath),
    wroteFiles: evidence.wroteFiles !== false && evidence.operation !== "skip",
    evidence,
  };
}

// ── append-profile ──────────────────────────────────────────────────────────

async function appendProfile({ section, content }, ctxObj) {
  if (!section) throw new Error(t("error.sectionRequired"));
  if (!content) throw new Error(t("error.contentRequired"));
  const evidence = appendProfileEntry({
    workspaceRoot: ctxObj.userWorkspaceRoot,
    entry: { section, content },
  });

  return {
    command: "append-profile",
    section,
    targetPath: ctxObj.userWorkspaceRoot ? path.relative(ctxObj.userWorkspaceRoot, evidence.target_path) : evidence.target_path,
    evidence,
  };
}

// ── append-topic ────────────────────────────────────────────────────────────

async function appendTopic({ slug, content }, ctxObj) {
  if (!slug) throw new Error(t("error.slugRequired"));
  if (!content) throw new Error(t("error.contentRequired"));
  const evidence = appendTopicEntry({
    workspaceRoot: ctxObj.userWorkspaceRoot,
    slug,
    entry: { content },
  });

  return {
    command: "append-topic",
    slug,
    targetPath: ctxObj.userWorkspaceRoot ? path.relative(ctxObj.userWorkspaceRoot, evidence.target_path) : evidence.target_path,
    evidence,
  };
}

// ── dispatcher ─────────────────────────────────────────────────────────────

async function main() {
  const args = parseArgs(process.argv.slice(2));

  const roots = validateRequiredRoots(args);
  const ctxObj = buildCliContext(roots);
  const mode = resolveMode(args);

  let data;
  switch (args.command) {
    case "promote":
      data = await promote({ sourcePath: args.sourcePath, targetSlug: args.targetSlug, mode }, ctxObj);
      break;
    case "digest":
      data = await digest({ period: args.period }, ctxObj);
      break;
    case "append-profile":
      data = await appendProfile({ section: args.section, content: args.content }, ctxObj);
      break;
    case "append-topic":
      data = await appendTopic({ slug: args.slug, content: args.content }, ctxObj);
      break;
    default:
      throw new Error(t("error.unknownCommand", { command: args.command || "(empty)" }));
  }

  emitResult(data, args.format);
}

main().catch((error) => {
  console.error(error.message || String(error));
  process.exitCode = 1;
});
